# Generated by Django 3.0.8 on 2022-08-02 16:25

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='Perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuario', models.CharField(max_length=20, unique=True)),
                ('clave', fernet_fields.fields.EncryptedTextField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Persona.Personas')),
            ],
        ),
        migrations.CreateModel(
            name='RolesPersonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_persona', to='Persona.Personas')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Persona.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Custodiados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Persona.Usuarios')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Persona.Personas')),
            ],
        ),
    ]
